### ISSUE TITLE
Ya v shoke

### ISSUE THREAD

**Issue by RenamQ** [Cristalix-Scripts/scripts#1]
Helloy dear razrabotchiki this scripts!
S posledney obnovoy nixyia ne working...
Ya zakinyl vse files from repositoriy v papku` C:\Users\%username%\.cristalix\updates\Minigames\scripts` i nifiga ne vorking!!
Please help me
![image](https://user-images.githubusercontent.com/67383666/104567999-4b53ac00-5671-11eb-832d-6846b270e6dc.png)

**Comment by Nartsissov** [comment]
Hello.

Закидывай только CristalixHelper.
